### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by gabwhoop** [bigtreetech/MMU2-DIP#1]
any manual to how to compile mmu2 firmware???? this manual is not complete, im using vscode to compile my printers firmware without any issues but with mmu2 the check mark to compile doen't apear....big thanx im sorry for my english

**Comment by bigtreetech** [comment]
Hi, we have tested the firmware to compile. You may need to wait for vscode to download the library.

**Comment by gabwhoop** [comment]
ok big thanx my problem was i try to open the file using vscode instead platformIO thanx for your time
