### ISSUE TITLE
3d model 3DModel/Electronics%20cover%20MMU2.STL is not good

### ISSUE THREAD

**Issue by ellensp** [bigtreetech/MMU2-DIP#17]
This is a very bad model. Almost nothing lines up. 
Considering you make the PCB and have all the dimensions, this is really not acceptable.

With USB on the left and PCB up with component on top for orientation

The two screw mounts on the bottom are ok. Why isn't there a 3rd one ?

Hole for USB is not tall enough.You cannot insert provided USB cable into the port, and if you try you will rip the USB port off of the PCB.

Reset button hole does not line up with reset button, hole is two low.

Indicator LEDs do not align up with the holes for them, To far left and incorrect spacing. Left most hole is out by 3.5 mm!

Button holes are all off center. Two far right and incorrect spacing.

Please try again. Or provide CAD so we can fit it

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/bigtreetech/MMU2-DIP/pull/19
