### ISSUE TITLE
MMU2-DIP will not reset on reset line 

### ISSUE THREAD

**Issue by ellensp** [bigtreetech/MMU2-DIP#18]
I have a brand new MMU2-DIP

I  connected to a FTDI interface to it since I was having issue getting it to communicate to do some diagnosis

FTDI -> P1 on MMU2-DIP
5v -> 5v
RX-TX
TX-RX
GND-GND

It powers on and says "start" @ 115200 baud as it should.

When I press the reset button on the side it resets as expected and the D8 LED lights up RED momentarily and It says start again over serial.

But when I connect the reset pin on P1 to GND momentarily, It does not restart, D8 LED does not light up and I don't get a start message,

The P1 reset line is required for the MMU2 to work. (with hardware reset mode) 

Please advise.

I could diagnose this further, if you had uploaded a circuit diagram as requested,
Edit: Circuit diagrams has just been uploaded.

Update. If I use reset pin on ICSP header, it resets as expected,
If I measure voltage on reset pin on ICSP header I get 3.3v pull up as I would expect
But if I measure voltage on reset pin on P1, I get nothing.

**Comment by ellensp** [comment]
Please Confirm that a hardware reset of the MMU2-DIP by momentarily holding reset pin on P1 low is meant to work.
Switching to software reset and sending X0 over serial to MMU2-DIP resets as expected.

**Comment by geheimo66** [comment]
for the reset, you have to remove the capacitor c15 at the reset button. then the reset works via p1.
